# Generated by Django 3.0.5 on 2020-12-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('currency', models.CharField(max_length=10)),
                ('type_product', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
            ],
        ),
    ]
