# Generated by Django 3.0.5 on 2020-12-09 09:58

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_card_list_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='list_cart',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, default=None, null=True, size=None),
        ),
    ]
